SurveyApp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('survey.urls')),
    # url(r'^', include(('survey.urls', 'survey'), namespace='survey')),

]

survey/urls.py
"""
Survey app url's
"""

from django.urls import path, include
from django.conf.urls import url
from survey import views

urlpatterns = [
    path('', views.index, name='index'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('signup/', views.signup, name='signup'),
    path('assignOrganization/', views.assign_organization, name='assign_organization'),
    path('organization/', views.organization, name='organization'),
    path('organizationArchive/', views.organization_archive, name='organization_archive'),
    path('updateOrg/', views.update_org, name='updateOrg'),
    url(r'^(?P<org_id>[0-9]+)/archiveOrg/$', views.archive_org, name='archiveOrg'),
    url(r'^(?P<org_id>[0-9]+)/restoreOrg/$', views.restore_org, name='restore_org'),
    path('emplList/', views.empl_list, name='emplList'),
    url(r'^(?P<empl_id>[0-9]+)/updateEmpl/$', views.update_empl, name='updateEmpl'),
    url(r'^(?P<empl_id>[0-9]+)/editEmpl/$', views.edit_empl, name='editEmpl'),
    url(r'^(?P<empl_id>[0-9]+)/deleteEmpl/$', views.delete_empl, name='deleteEmpl'),
    # path('profile/', views.update_profile, name='profile'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
    url(r'^questList', views.quest_list, name='questList'),
    url(r'^addQuest', views.AddQuest.as_view(), name='addQuest'),
    path('saveQuest/', views.save_quest, name='saveQuest'),
    path('updateQuest/', views.update_quest, name='updateQuest'),
    url(r'^(?P<quest_id>[0-9]+)/delete_question/$', views.delete_question, name='deleteQuestion'),
    path('surveyList', views.survey_list, name='surveyList'),
    url(r'^addSurvey', views.add_survey, name='addSurvey'),
    path('saveSurvey/', views.save_survey, name='saveSurvey'),
    path('schedule_survey/', views.schedule_survey, name='schedule_survey'),
    url(r'^(?P<survey_id>[0-9]+)/surveyQuest/$', views.survey_quest, name='surveyQuest'),
    url(r'^(?P<survey_id>[0-9]+)/assignSurvey/$', views.assign_survey, name='assignSurvey'),
    url(r'^(?P<survey_id>[0-9]+)/deleteSurvey/$', views.delete_survey, name='deleteSurvey'),
    path('saveAssignSurvey/', views.save_assign_survey, name='saveAssignSurvey'),
    path('surveyListEmployee', views.survey_list_employee, name='surveyListEmployee'),
    url(r'(?P<survey_id>[0-9]+)/surveyQuestEmployee/$', views.survey_quest_employee,
        name='surveyQuestEmployee'),
    url(r'(?P<survey_id>[0-9]+)/saveSurveyAnswers/$', views.save_survey_answers,
        name='saveSurveyAnswers'),
    url(r'(?P<survey_id>[0-9]+)/surveyQuestResultEmployee/$', views.survey_quest_result_employee,
        name='surveyQuestResultEmployee'),
    url(r'^uploadEmplCSV/$', views.upload_empl_csv, name='uploadEmplCSV'),
    url(r'^reports/$', views.reports, name='reports'),
]

survey/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


# survey app models
class Organization(models.Model):
    name = models.CharField(max_length=50)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class User(AbstractUser):
    is_org_admin = models.BooleanField(default=False)
    is_employee = models.BooleanField(default=False)
    organization = models.ForeignKey(Organization, on_delete=models.CASCADE, null=True)


class Questions_library(models.Model):
    type = models.CharField(max_length=2)
    title = models.CharField(max_length=256)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = u'Questions_library'

    def __str__(self):
        return self.title


class ques_choices(models.Model):
    questions = models.ForeignKey(Questions_library, on_delete=models.CASCADE)
    choice = models.CharField(max_length=256)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.choice


class Survey(models.Model):
    name = models.CharField(max_length=200)
    s_date = models.DateField(null=True)
    e_date = models.DateField(null=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Survey_QuesMap(models.Model):
    survey_id = models.ForeignKey(Survey, on_delete=models.CASCADE)
    question_id = models.ForeignKey(Questions_library, on_delete=models.CASCADE)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class SurveyEmployeeMap(models.Model):
    survey_id = models.ForeignKey(Survey, on_delete=models.CASCADE)
    empl_id = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Survey_Result(models.Model):
    survey = models.ForeignKey(Survey, on_delete=models.CASCADE)
    empl = models.ForeignKey(User, on_delete=models.CASCADE)
    question = models.ForeignKey(Questions_library, on_delete=models.CASCADE)
    answer = models.CharField(max_length=256)
    answer_status = models.BooleanField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.answer

survey/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth import get_user_model
User = get_user_model()

class SignupForm(UserCreationForm):
    email = forms.EmailField(max_length=200, help_text='Required')
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

survey/views.py
"""
All views of Survey Project
"""
import csv
from io import StringIO
import re
import datetime
import logging
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.models import User
from django.core.mail import EmailMessage
from django.core.paginator import Paginator
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.http import QueryDict
from .forms import SignupForm
from .tokens import account_activation_token
from .models import Questions_library, ques_choices, Survey, Survey_QuesMap, \
    SurveyEmployeeMap, Survey_Result, Organization
from . import models

User = get_user_model()
logger = logging.getLogger(__name__)


@login_required(login_url='login')
def index(request):
    if request.user.is_employee:
        return redirect('surveyListEmployee')
    else:
        return render(request, 'survey/index.html')


# check user is superuser
def is_user_superuser():
    return lambda u: u.is_superuser


def is_user_orgadmin():
    return lambda u: u.is_org_admin


def is_user_orgadmin_or_superuser():
    return lambda u: u.is_superuser or u.is_org_admin


@user_passes_test(is_user_orgadmin_or_superuser())
@login_required(login_url='login')
def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            try:
                user_obj = form.save(commit=False)
                user_obj.is_active = True
                if request.user.is_superuser:
                    user_obj.is_org_admin = True
                elif request.user.is_org_admin:
                    user_obj.is_employee = True
                    user_obj.organization = request.user.organization
                user_obj.save()
            except Exception as exception:
                logger.error(exception)
                messages.error(request, 'Error!!!')
                return redirect('emplList')

            messages.success(request, 'Saved!!!')
            return redirect('emplList')
        else:
            messages.success(request, form.errors)

    form = SignupForm()
    org_list = Organization.objects.all()
    return render(request, 'survey/signup.html', {'form': form, 'org_list': org_list})


def validate_csv(csv_file):
    msg = ""
    status = False
    if not csv_file.name.endswith('.csv'):
        msg = "File is not CSV type"
        status = False
    elif csv_file.multiple_chunks():
        msg = "Uploaded file is too big (%.2f MB)."
        status = False
    else:
        msg = "valid file"
        status = True
    return status, msg


def read_post_csv(csv_file):
    csvf = StringIO(csv_file.read().decode())
    return csv.reader(csvf)


def is_valid_email(email):
    return bool(re.search(r"^[\w\.\+\-]+\@[\w]+\.[a-z]{2,3}$", email))


@user_passes_test(is_user_orgadmin())
@login_required(login_url='login')
def upload_empl_csv(request):
    is_csv_data_valid = False
    csv_data_msg = ''

    try:
        csv_file = request.FILES["empl_csv"]
        is_valid, err_msg = validate_csv(csv_file)
        if not is_valid:
            messages.error(request, err_msg)
            return redirect('emplList')

        empl_csv_data = read_post_csv(csv_file)
        for empl_data in empl_csv_data:
            data_dict = {}
            data_dict["csrfmiddlewaretoken"] = request.POST['csrfmiddlewaretoken']
            data_dict["username"] = empl_data[0]
            if is_valid_email(empl_data[1]):
                data_dict["email"] = empl_data[1]
            else:
                messages.error(request, "Email of employees is not valid !")
                return redirect('emplList')

            data_dict["password1"] = empl_data[2]
            data_dict["password2"] = empl_data[2]
            qdict = QueryDict('', mutable=True)
            qdict.update(data_dict)
            form = SignupForm(qdict)
            if form.is_valid():
                user_obj = form.save(commit=False)
                user_obj.is_active = True
                user_obj.is_employee = True
                user_obj.organization = request.user.organization
                user_obj.save()
                is_csv_data_valid = True
            else:
                is_csv_data_valid = False
        if is_csv_data_valid:
            csv_data_msg = 'Saved Successfully !'
        else:
            csv_data_msg = 'username must be unique, password should be 8 character and strong!'

        messages.error(request, csv_data_msg)
        return redirect('emplList')

    except Exception as exception:
        logger.error(exception)
        messages.error(request, "Unable to upload file. ")
    return redirect('emplList')


@user_passes_test(is_user_orgadmin_or_superuser())
@login_required(login_url='login')
def empl_list(request):
    if request.user.is_superuser:
        users = User.objects.filter(is_org_admin=True)
    else:
        users = User.objects.filter(organization=request.user.organization)
    org_list = Organization.objects.all()
    return render(request, 'survey/employeesList.html', {'users': users, 'org_list': org_list})


@user_passes_test(is_user_superuser())
@login_required(login_url='login')
def assign_organization(request):
    User.objects.filter(id=request.POST['user_id']).update(organization=request.POST['organization'])
    messages.success(request, 'Assigned successfully!')
    return redirect('emplList')


@user_passes_test(is_user_orgadmin_or_superuser())
@login_required(login_url='login')
def edit_empl(request, empl_id):
    user_info = User.objects.only('first_name', 'email').get(pk=empl_id)
    return render(request, 'survey/edit_employee.html',
                  {"empl_id": empl_id, 'user_info': user_info})


@user_passes_test(is_user_orgadmin_or_superuser())
@login_required(login_url='login')
def update_empl(request, empl_id):
    User.objects.filter(pk=empl_id).update(email=request.POST['email'],
                                           first_name=request.POST['name'])
    messages.success(request, 'Updated successfully!')
    return redirect('emplList')


@user_passes_test(is_user_orgadmin_or_superuser())
@login_required(login_url='login')
def delete_empl(request, empl_id):
    user = get_object_or_404(User, pk=empl_id)
    user.delete()
    messages.success(request, 'Deleted successfully!')
    return redirect('emplList')


@user_passes_test(is_user_superuser())
@login_required(login_url='login')
def organization(request):
    if request.method == 'POST':
        organization = Organization()
        organization.name = request.POST['org_name']
        organization.save()
        messages.success(request, 'Saved successfully!')
        return redirect('organization')
    else:
        org_list = Organization.objects.filter(is_active=True)
        return render(request, 'survey/organization.html', {"org_list": org_list})


@user_passes_test(is_user_superuser())
@login_required(login_url='login')
def organization_archive(request):
    org_list = Organization.objects.filter(is_active=False)
    return render(request, 'survey/organization_archive.html', {"org_list": org_list})

@user_passes_test(is_user_superuser())
@login_required(login_url='login')
def update_org(request):
    Organization.objects.filter(id=request.POST['org_id']).update(name=request.POST['name'])
    messages.success(request, 'Updated successfully!')
    return redirect('organization')


@user_passes_test(is_user_superuser())
@login_required(login_url='login')
def archive_org(request, org_id):
    Organization.objects.filter(id=org_id).update(is_active=False)
    return redirect('organization')


@user_passes_test(is_user_superuser())
@login_required(login_url='login')
def restore_org(request, org_id):
    Organization.objects.filter(id=org_id).update(is_active=True)
    return redirect('organization_archive')


@login_required(login_url='login')
def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        return HttpResponse('Thank you for your email confirmation. '
                            'Now you can login your account.')
    else:
        return HttpResponse('Activation link is invalid!')


# Questions curds
@user_passes_test(is_user_orgadmin())
@login_required(login_url='login')
def quest_list(request):
    questions_list = Questions_library.objects.filter(created_by=request.user.id)
    return render(request, 'survey/questions.html', {"questions_list": questions_list})


class AddQuest(ListView):
    context_object_name = 'survey_questions_library'
    model = models.Questions_library
    template_name = 'survey/add_questions.html'


@user_passes_test(is_user_orgadmin())
@login_required(login_url='login')
def save_quest(request):
    if request.method == 'POST':
        quest = Questions_library()
        quest.title = request.POST['title']
        quest.type = request.POST['type']
        quest.created_by = User.objects.get(id=request.user.id)
        quest.save()
        if request.POST['choices']:
            for x in request.POST['choices'].split(','):
                ques_c = ques_choices()
                ques_c.questions = quest
                ques_c.choice = x
                ques_c.created_by = User.objects.get(id=request.user.id)
                ques_c.save()
        messages.success(request, 'Added successfully!')
        return redirect('questList')


@user_passes_test(is_user_orgadmin())
@login_required(login_url='login')
def update_quest(request):

survey/templates/survey/add_questions.html
{% extends 'survey/base.html' %}

{% block content %}
  <h4>Add Question</h4>
    <form class="form-horizontal" method="post" action="{% url 'saveQuest' %}">
      {% csrf_token %}
      <div class="form-group">
        <label class="control-label col-sm-2" >Question Title:</label>
        <div class="col-sm-12">
          <input type="text" class="form-control" name="title" required>
        </div>
      </div>
      <div class="form-group">
        <label class="control-label col-sm-2" >Type:</label>
        <div class="col-sm-12">
          <select class="form-control" name="type" id="type" required>
            <option value="">Select type</option>
            <option value="1">Choices</option>
            <option value="2">Text Field</option>

          </select>
        </div>
        <div style="display:none" id="choices">
          <label class="control-label col-sm-2" >Enter choices:</label>
          <div class="col-sm-12">
            <input type="text" class="form-control" name="choices">
          </div>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <button type="submit" class="btn btn-primary">Submit</button>
        </div>
      </div>
    </form>

    <script>
      $('#type').change(function(){
        if($(this).val() == '1'){
          $('#choices').css("display","block")
        }
        else{
          $('#choices').css("display","none")
        }
      });
    </script>
{% endblock %}

survey/templates/survey/add_survey.html
{% extends 'survey/base.html' %}

{% block content %}
  <h5>Add Survey</h5>
    <form class="form-horizontal" method="post" action="{% url 'saveSurvey' %}">
      {% csrf_token %}
      <div class="form-group">
        <label class="control-label col-sm-2" >Survey Name:</label>
        <div class="col-sm-12">
          <input type="text" class="form-control" name="name" required>
        </div>
      </div>
      <div class="form-group">
        <ul class="list-group col-sm-12">
            {% for question in questions_list %}
                <li class="list-group-item">
                      <label><input type="checkbox" value="{{ question.id }}" name="question_id">{{ question.title }}</label>
                </li>
            {% endfor %}
        </ul>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <button type="submit" class="btn btn-primary">Submit</button>
        </div>
      </div>
    </form>

{% endblock %}

survey/templates/survey/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Survey Project</title>
  <!-- Bootstrap core CSS -->
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <!-- Custom styles for this template -->
  <link href="{% static 'css/simple-sidebar.css' %}" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</head>
<body>
  <div class="d-flex" id="wrapper">
    <!-- Sidebar -->
    <div class="border-right sidebar-wrapper" id="sidebar-wrapper">
      <div class="sidebar-heading" style="background: #cdd422;">Survey Application</div>
      <div class="list-group list-group-flush">
        {% if user.is_authenticated %}
          {% if request.user.is_superuser %}
            <!--<a href="{% url 'admin:index' %}" class="list-group-item list-group-item-action bg-light" target="_blank">Django Admin</a>-->
            <a href="{% url 'organization' %}" class="list-group-item list-group-item-action">Organization</a>
            <a href="{% url 'emplList' %}" class="list-group-item list-group-item-action">Organization Admin</a>
          {% elif request.user.is_org_admin %}
            {% if request.user.organization.is_active %}
              <a href="{% url 'emplList' %}" class="list-group-item list-group-item-action">Employee</a>
              <a href="{% url 'questList' %}" class="list-group-item list-group-item-action">Questions</a>
              <a href="{% url 'surveyList' %}" class="list-group-item list-group-item-action">Survey</a>
              <a href="{% url 'reports' %}" class="list-group-item list-group-item-action">Reports</a>
            {% endif %}
          {% else %}
            {% if request.user.organization.is_active %}
              <a href="{% url 'surveyListEmployee' %}" class="list-group-item list-group-item-action">Your Survey</a>
            {% endif %}
          {% endif %}
        {% endif %}

      </div>
    </div>
    <!-- /#sidebar-wrapper -->

    <!-- Page Content -->
    <div id="page-content-wrapper">

      <nav class="navbar navbar-expand-lg navbar-light border-bottom">
        <a id="menu-toggle"><i class="fa fa-bars"></i> </a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
            {% if user.is_authenticated %}
              <li class="nav-item active">
                <p>Welcome, {{ user.get_username }}</p>
              </li>
              <li class="nav-item active">
                <a href="{% url 'logout' %}" class="sign">Logout</a>
              </li>
            {% else %}
              <li class="nav-item active">
                  <a href="{% url 'login' %}" class="sign">Login</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </nav>

      <div class="container-fluid">
          {% block content %}
          {% endblock %}
      </div>
    </div>
    <!-- /#page-content-wrapper -->

  </div>
  <!-- /#wrapper -->


  <!-- Menu Toggle Script -->
  <script>
    $("#menu-toggle").click(function(e) {
      e.preventDefault();
      $("#wrapper").toggleClass("toggled");
    });
  </script>

</body>

</html>

survey/templates/survey/edit_employee.html
{% extends 'survey/base.html' %}

{% block content %}
{% if messages %}
    <div class="alert alert-success">
        {% for message in messages %}
            <strong>Success!</strong> {{ message }}
        {% endfor %}
    </div>
{% endif %}
    <form method="post" action="{% url 'updateEmpl' empl_id %}">
        {% csrf_token %}
        <div class="form-group">
            <label class="control-label col-sm-2" >Name:</label>
            <div class="col-sm-10">
              <input type="text" class="form-control" name="name" value="{{user_info.first_name}}">
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-sm-2" >Email:</label>
            <div class="col-sm-10">
              <input type="text" class="form-control" name="email" value="{{user_info.email}}">
            </div>
        </div>
        <button type="submit" class="btn btn-primary">Update</button>
    </form>
{% endblock %}

survey/templates/survey/index.html
{% extends "survey/base.html" %}

{% block content %}
    <h4 class="wl-ti">Welcome to Survey Application</h4>
    {% if not request.user.organization.is_active %}
        {% if not request.user.is_superuser %}
            <h6> Your organization is inactive now</h6>
        {% endif %}
    {% endif %}
{% endblock %}

survey/templates/survey/organization.html
{% extends 'survey/base.html' %}

{% block content %}
{% if messages %}
    <div class="alert alert-success">
        {% for message in messages %}
            <strong>Success!</strong> {{ message }}
        {% endfor %}
    </div>
{% endif %}
  <form class="form-horizontal" method="POST" action="{% url 'organization' %}">
      {% csrf_token %}
      <div class="form-group">
        <label class="control-label col-sm-4" >Add Organization</label>
        <div class="col-sm-12">
          <input type="text" class="form-control" name="org_name" placeholder="Enter organization name" required>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <button type="submit" class="btn btn-primary">Save</button>
        </div>
      </div>
    </form>

    <h5>Organizations List</h5>
    <div class="btn btn-warning"><a href="{% url 'organization_archive' %}">Archive Data</a></div>
    </br></br>
    <div class="card">
        <ul class="list-group">
            {% for org in org_list %}
                <li class="list-group-item" data-id="{{ org.id }}" data-name="{{ org }}">{{ org }}
                    <div class="text-right" style="float: right;">
                        <a href="#" id="edit-btn" data-toggle="modal" data-target="#edit"><span class="fa fa-pencil text-right" ></span></a>
                        <a href="{% url 'archiveOrg' org.id %}" onclick="return confirm('Are you sure you want to archive this item?');"><span class="fa fa-archive text-right text-success"></span></a>
                    </div>
                </li>
            {% endfor %}
        </ul>
    </div>

<!-- Modal -->
      <div class="modal fade" id="edit" role="dialog">
        <div class="modal-dialog">

          <!-- Modal content-->
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title">Update Organization</h5>
            </div>
            <div class="modal-body">
                <form method="post" action="" id="edit-form">
                    {% csrf_token %}
                    <div class="form-group">
                        <input type="hidden" class="form-control" id="org_id" name="org_id">
                        <label class="control-label col-sm-2" >Title:</label>
                        <div class="col-sm-12">
                          <input type="text" class="form-control" id="name" name="name">
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary">Update</button>
                    <button type="button" class="btn btn-danger" data-dismiss="modal" style="float:right">Close</button>
                </form>
            </div>
          </div>

        </div>
      </div>
<script>
    $('.fa-pencil').click(function(){
        quest_id = $(this).parent().parent().parent().attr('data-id')
        quest_title = $(this).parent().parent().parent().attr('data-name')
        $('#edit-form #org_id').val(quest_id);
        $('#edit-form #name').val(quest_title);
        $('#edit-form').attr('action', "{% url 'updateOrg' %}");
    });
</script>
{% endblock %}

survey/templates/survey/profile.html
{% extends 'survey/base.html' %}

{% block content %}
{% if messages %}
    <div class="alert alert-success">
        {% for message in messages %}
            <strong>Success!</strong> {{ message }}
        {% endfor %}
    </div>
{% endif %}
  <form method="post">
    {% csrf_token %}
    {{ user_form.as_p }}
    {{ profile_form.as_p }}
    <button type="submit" class="btn btn-primary">Save changes</button>
  </form>
{% endblock %}

survey/templates/survey/signup.html
{% extends 'survey/base.html' %}

{% block content %}
{% if messages %}
    <div class="alert alert-danger">
        {% for message in messages %}
            {{ message }}
        {% endfor %}
    </div>
{% endif %}
  <form method="post">
    {% csrf_token %}
      {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
          <small>{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
      {% endfor %}

    <button type="submit" class="btn btn-primary">Save</button>
  </form>
{% endblock %}

survey/templates/survey/survey_assign.html
{% extends 'survey/base.html' %}

{% block content %}
    <h5>Assign Survey to users</h5>
     <form class="form-horizontal" method="post" action="{% url 'saveAssignSurvey' %}">
          {% csrf_token %}
        <input type="hidden" value="{{survey_id}}" name="survey_id">
        <div class="card">
            <ul class="list-group">
                {% for user in user_list %}
                <li class="list-group-item">
                    <label><input type="checkbox" value="{{ user.id }}" name="emp_id">{{user.username}}, Email: {{user.email}}</label>
                </li>
                {% endfor %}
            </ul>
        </div>

         <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <button type="submit" class="btn btn-primary">Submit</button>
            </div>
         </div>
     </form>
{% endblock %}